### ISSUE TITLE
About projection in AttentionLayer

### ISSUE THREAD

**Issue by somaonishi** [MAZiqing/FEDformer#57]
Hi, I am glad to have found your interesting research.

I have a question about your code.

The projection in your code is different from AttentionLayer in vanila Transformer, please tell me your intention.
Specifically, the code below includes bias in the projection, but the vanila Transformer projection has `bias=False`. I would like to know if there is any reason why it is more accurate to use `bias=True` for time series data, etc.

https://github.com/MAZiqing/FEDformer/blob/0e28af8a03fd5971933d4b3dca6c9bc09c2a8109/layers/SelfAttention_Family.py#L143-L145

https://github.com/MAZiqing/FEDformer/blob/0e28af8a03fd5971933d4b3dca6c9bc09c2a8109/layers/MultiWaveletCorrelation.py#L114-L116

Best regards.

**Comment by tianzhou2011** [comment]
The decision to set bias to False in the projection layers of
MultiHeadAttention in vanila transformer is based on design considerations
rather than empirical evidence. There is no clear evidence that removing
biases from these projection layers necessarily leads to better performance
on a particular task. They want to ensure that the attention scores are
computed solely based on the dot product of the projected queries and keys.
Here we add bias since it gives minor improvement overall.

**Comment by somaonishi** [comment]
Thank you for your prompt reply!!
